<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class PatientClinicalHistory extends Model
{
    protected $fillable = [
        'patient_id',
        'fam_father',
        'fam_mother',
        'fam_grandparents',
        'fam_uncles',
        'fam_siblings',
        'has_vertigo',
        'has_otalgia',
        'has_otorrhea',
        'has_serous_otitis',
        'has_ear_obstruction',
        'has_ossicular_chain_lesion',
        'has_meniere',
        'has_trauma',
        'has_meningitis',
        'has_facial_paralysis',
        'has_herpes_zoster',
        'has_mumps',
        'has_rubella',
        'has_measles',
        'has_typhoid',
        'has_typhus',
        'use_streptomycin',
        'use_gentamicin',
        'uses_salicylates',
        'uses_quinine',
        'use_kanamycin',
        'use_tobramycin',
        'use_furosemide',
        'use_ethacrynic_acid',
        'use_vancomycin',
        'has_malaria',
        'has_rheumatism',
        'has_tuberculosis',
        'has_headaches',
        'has_heart_failure',
        'has_hypertension',
        'hearing_loss_type',
        'hearing_loss_degree',
        'has_hearing_aid',
        'hearing_aid_side',
        'has_cochlear_implant',
        'cochlear_implant_side',
        'ambient_noise_improvement',
        'loud_noise_annoyance',
        'physical_exam_notes',
        'otologics_history',
    ];

    protected $casts = [
        'fam_father' => 'boolean',
        'fam_mother' => 'boolean',
        'fam_grandparents' => 'boolean',
        'fam_uncles' => 'boolean',
        'fam_siblings' => 'boolean',
        'has_vertigo' => 'boolean',
        'has_otalgia' => 'boolean',
        'has_otorrhea' => 'boolean',
        'has_serous_otitis' => 'boolean',
        'has_ear_obstruction' => 'boolean',
        'has_ossicular_chain_lesion' => 'boolean',
        'has_meniere' => 'boolean',
        'has_trauma' => 'boolean',
        'has_meningitis' => 'boolean',
        'has_facial_paralysis' => 'boolean',
        'has_herpes_zoster' => 'boolean',
        'has_mumps' => 'boolean',
        'has_rubella' => 'boolean',
        'has_measles' => 'boolean',
        'has_typhoid' => 'boolean',
        'has_typhus' => 'boolean',
        'use_streptomycin' => 'boolean',
        'use_gentamicin' => 'boolean',
        'uses_salicylates' => 'boolean',
        'uses_quinine' => 'boolean',
        'use_kanamycin' => 'boolean',
        'use_tobramycin' => 'boolean',
        'use_furosemide' => 'boolean',
        'use_ethacrynic_acid' => 'boolean',
        'use_vancomycin' => 'boolean',
        'has_malaria' => 'boolean',
        'has_rheumatism' => 'boolean',
        'has_tuberculosis' => 'boolean',
        'has_headaches' => 'boolean',
        'has_heart_failure' => 'boolean',
        'has_hypertension' => 'boolean',
        'has_hearing_aid' => 'boolean',
        'has_cochlear_implant' => 'boolean',
        'ambient_noise_improvement' => 'boolean',
        'loud_noise_annoyance' => 'boolean',
    ];

    public function patient()
    {
        return $this->belongsTo(Patient::class);
    }
}
